import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export const store = new Vuex.Store({
    state: {
        tier : {
        banjoandkazooie : 'D',
        bayonetta : 'F',
        blyeth : 'E',
        bowser : 'C',
        bowserjr : 'F',
        byleth : 'E',
        captainfalcon : 'E',
        chrom : 'B',
        cloud : 'C',
        corrin : 'F',
        daisy : 'A',
        darkpit : 'F',
        pokemontrainer : 'B',
        darksamus : 'C',
        diddykong : 'D',
        donkeykong : 'F',
        drmario : 'F',
        duckhunt : 'D',
        falco : 'D',
        fox : 'B',
        ganondorf : 'F',
        greninja : 'B',
        hero : 'D',
        iceclimbers : 'E',
        ike : 'D',
        incineroar : 'F',
        inkling : 'B',
        isabelle : 'F',
        jigglypuff : 'F',
        joker : 'A',
        ken : 'C',
        kingdedede : 'F',
        kingkrool : 'F',
        kirby : 'F',
        link : 'C',
        littlemac : 'F',
        lucario : 'E',
        lucas : 'D',
        lucina : 'B',
        luigi : 'D',
        mario : 'B',
        marth : 'D',
        megaman : 'B',
        metaknight : 'E',
        mewtwo : 'F',
        miibrawler : 'E',
        miiswordfighter : 'E',
        miigunner : 'F',
        minmin : 'D',
        gameandwatch : 'B',
        ness : 'C',
        olimar : 'B',
        pacman : 'B',
        palutena : 'A',
        peach : 'A',
        pichu : 'C',
        pikachu : 'A',
        piranhaplant : 'E',
        pit : 'F',
        richter : 'E',
        ridley : 'E',
        rOB : 'B',
        robin : 'F',
        rosalinaandluma : 'D',
        roy : 'B',
        ryu : 'C',
        samus : 'C',
        sheik : 'E',
        shulk : 'B',
        simon : 'E',
        snake : 'B',
        sonic : 'C',
        terry : 'C',
        toonlink : 'D',
        villager : 'E',
        wario : 'B',
        wiifittrainer : 'D',
        wolf : 'B',
        yoshi : 'C',
        youngLink : 'C',
        zelda : 'E',
        zerosuitsamus : 'A',
        } 
    },
    getters: {
        getTier: (state) => (name) => {
            return state.tier[name]
        }
    }
})