import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export const store = new Vuex.Store({
    state: {
        tier : {
        Banjoandkazooie : 'Mid',
        Bayonetta : 'Low',
        Blyeth : 'Low+',
        Bowser : 'Mid+',
        Bowserjr : 'Low',
        Byleth : 'Low+',
        Captainfalcon : 'Low+',
        Chrom : 'High',
        Cloud : 'Mid+',
        Corrin : 'Low',
        Daisy : 'TOP',
        Darkpit : 'Low',
        Pokemontrainer : 'High',
        Darksamus : 'Mid+',
        Diddykong : 'Mid',
        Donkeykong : 'Low',
        Drmario : 'Low',
        Duckhunt : 'Mid',
        Falco : 'Mid',
        Fox : 'High',
        Ganondorf : 'Low',
        Greninja : 'High',
        Hero : 'Mid',
        Iceclimbers : 'Low+',
        Ike : 'Mid',
        Incineroar : 'Low',
        Inkling : 'High',
        Isabelle : 'Low',
        Jigglypuff : 'Low',
        Joker : 'TOP',
        Ken : 'Mid+',
        Kingdedede : 'Low',
        Kingkrool : 'Low',
        Kirby : 'Low',
        Link : 'Mid+',
        Littlemac : 'Low',
        Lucario : 'Low+',
        Lucas : 'Mid',
        Lucina : 'High',
        Luigi : 'Mid',
        Mario : 'High',
        Marth : 'Mid',
        Megaman : 'High',
        Metaknight : 'Low+',
        Mewtwo : 'Low',
        Miibrawler : 'Low+',
        Miiswordfighter : 'Low+',
        Miigunner : 'Low',
        Minmin : 'Mid',
        Gameandwatch : 'High',
        Ness : 'Mid+',
        Olimar : 'High',
        Pacman : 'High',
        Palutena : 'TOP',
        Peach : 'TOP',
        Pichu : 'Mid+',
        Pikachu : 'TOP',
        Piranhaplant : 'Low+',
        Pit : 'Low',
        Richter : 'Low+',
        Ridley : 'Low+',
        ROB : 'High',
        Robin : 'Low',
        Rosalinaandluma : 'Mid',
        Roy : 'High',
        Ryu : 'Mid+',
        Samus : 'Mid+',
        Sheik : 'Low+',
        Shulk : 'High',
        Simon : 'Low+',
        Snake : 'High',
        Sonic : 'Mid+',
        Terry : 'Mid+',
        Toonlink : 'Mid',
        Villager : 'Low+',
        Wario : 'High',
        Wiifittrainer : 'Mid',
        Wolf : 'High',
        Yoshi : 'Mid+',
        YoungLink : 'Mid+',
        Zelda : 'Low+',
        Zerosuitsamus : 'TOP',
        } 
    },
    getters: {
        getTier: (state) => (name) => {
            return state.tier[name]
        }
    }
})